dist: focal

language: python
python:
  - 3.7

install:
 - pip install --upgrade pip
 - pip install black codecov coverage isort flake8
 - pip install cython

script:
 - black --check .
 - flake8 --max-line-length=88 .
 - isort --check-only --diff *.py rocc tests
 - coverage run --include="./*" --omit="docs/","*/tests/*","*/tests.py","setup.py" ./setup.py test
 
after_success:
  - codecov
